# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/umv
# Target is a library:  

CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib 
HEADERS += Pallet.h \
           pallets.h \
           umvview.h 
SOURCES += Pallet.cpp \
           umvview.cpp 
