# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/dendrogram
# Target is a library:  

INCLUDEPATH += ../../src/spa 
CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib 
HEADERS += dendrogram.h \
           dendrogramwidget.h 
SOURCES += dendrogram.cpp \
           dendrogramwidget.cpp 
