# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/spa
# Target is a library:  

CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib 
HEADERS += PretopologicalMetricSpace.h \
           PretopologicalSpace.h \
           Set.h \
           SpaException.h \
           Set.cpp 
SOURCES += PretopologicalMetricSpace.cpp \
           PretopologicalSpace.cpp 
